import { SlideShell } from "../slide-shell"

const layers = [
  {
    n: "1",
    title: "Embedded Wallet (EOA)",
    role: "Signer",
    body: "Generated by Privy at sign-up. Holds the key, signs UserOperations. Never appears on-chain.",
    color: "#8B78E6",
  },
  {
    n: "2",
    title: "Smart Wallet · Kernel (ERC-4337)",
    role: "On-chain actor",
    body: "Deployed by ZeroDev on the first transaction. Pays, receives NFTs, calls contracts. This is “your address” to the protocol.",
    color: "#6EE76E",
  },
  {
    n: "3",
    title: "EntryPoint (ERC-4337)",
    role: "Executor",
    body: "Global standard contract, same address on every EVM chain. Executes UserOps from the bundler on the Smart Wallet's behalf.",
    color: "#F25CA2",
  },
]

export function SlideWalletArchitecture() {
  return (
    <SlideShell
      eyebrow="Wallet Architecture"
      title="One builder, three identity layers."
      lead="Account Abstraction done right: the non-crypto builder never sees a seed phrase, and their personal address never touches the chain."
    >
      <div className="flex flex-col items-stretch gap-2">
        {layers.map((l, i) => (
          <div key={l.n} className="flex flex-col items-stretch gap-2">
            <div
              className="flex items-start gap-4 rounded-xl border bg-white/[0.04] p-4"
              style={{ borderColor: `${l.color}55` }}
            >
              <span
                className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg font-display text-sm font-bold"
                style={{ backgroundColor: `${l.color}1f`, color: l.color }}
              >
                {l.n}
              </span>
              <div className="flex-1">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="font-display text-sm font-bold text-white">
                    {l.title}
                  </span>
                  <span
                    className="rounded-full px-2 py-0.5 font-mono text-[10px] tracking-widest"
                    style={{ backgroundColor: `${l.color}1f`, color: l.color }}
                  >
                    {l.role}
                  </span>
                </div>
                <p className="mt-1 text-xs leading-relaxed text-[#9D9CB0]">
                  {l.body}
                </p>
              </div>
            </div>
            {i < layers.length - 1 && (
              <span className="text-center text-lg leading-none text-[#5A5680]">
                ↓
              </span>
            )}
          </div>
        ))}
      </div>

      <p className="mt-6 max-w-3xl text-sm leading-relaxed text-[#9D9CB0]">
        <span className="text-white">The golden rule:</span> you sign a{" "}
        <span className="font-mono text-[#8B78E6]">UserOperation</span>, not a
        transaction. The bundler (ZeroDev) builds the real Ethereum tx, pays the
        gas, and submits it to the EntryPoint for you.
      </p>
    </SlideShell>
  )
}
